Replaces sleeping related Mixins with somnus
williambl/haema pull request #28
Opened 2021-02-14 15:25 UTC by tyra314

This replaces the sleeping related Mixins, which were not compatible with Somnus, with Somnus itself. Redirect Mixins are inherently not compatible with each other, so all Mixins would have to be rewritten as @inject or something. Seems easier this way. If you can't beat them, join them, right?

Fixes #21

2021-02-14 15:40 UTC, williambl commented
Ah awesome, thanks!

2021-02-14 15:44 UTC, williambl requested changes
Thanks so much, just one little thing :)

2021-02-14 15:44 UTC, williambl commented on src/main/kotlin/com/williambl/haema/Haema.kt
Vampires can sleep in day too :)
```suggestion
```

2021-02-14 16:55 UTC, tyra314 commented on src/main/kotlin/com/williambl/haema/Haema.kt
I wasn't aware of that. Fixed it.

2021-02-15 19:07 UTC, williambl approved these changes

2021-02-15 21:53 UTC, merged